version: "3.9"
services:
  localstack:
    image: localstack/localstack:latest
    container_name: madmall-localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=dynamodb,s3,sqs,secretsmanager,apigateway,cloudwatch,logs,cognito
      - DEBUG=1
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - LOCALSTACK_SERVICES=dynamodb,s3,sqs,secretsmanager,apigateway,cloudwatch,logs,cognito
      - LOCALSTACK_HOST=localhost
    volumes:
      - localstack-data:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  localstack-data:
